---

- name: Configure RPM Fusion repositories
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Import public GPG keys for RPM Fusion
  rpm_key:
    state: present
    key: "{{ role_path }}/files/{{ item }}"
  loop:
    - RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}
    - RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}

- name: Install Packages for h264 playback in firefox
  dnf:
    state: latest
    name:
      - gstreamer1-plugin-openh264
      - mozilla-openh264
    enablerepo: fedora-cisco-openh264

- name: Install Packages for MP4 playback
  dnf:
    state: latest
    name:
      - ffmpeg-libs
      - ffmpeg
      - x264-libs
      - x265-libs
      - gstreamer-ffmpeg
      - gstreamer-plugins-bad
      - gstreamer-plugins-bad-free
      - gstreamer-plugins-bad-free-extras
      - gstreamer-plugins-good
      - gstreamer-plugins-good-extras
      - gstreamer-plugins-ugly
      - libmpeg2
      - gstreamer1-libav
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - gstreamer1-plugins-bad-freeworld
      - compat-ffmpeg28
      - mozilla-openh264
